# Generated by Django 6.0.4 on 2026-04-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'verbose_name': 'Wallpaper', 'verbose_name_plural': 'Wallpapers'},
        ),
    ]
