# Generated by Django 6.0.4 on 2026-04-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallpaperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wallpapers/')),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wallpaper.wallpaper')),
            ],
        ),
    ]
