# Generated by Django 6.0.4 on 2026-04-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_purchase_amount_purchase_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
    ]
