# Generated by Django 6.0.4 on 2026-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_remove_purchase_amount_remove_purchase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
